# A string used to distinguish different Supabase projects on the same host.
project_id = "apnipost_admin"

[api]
enabled = true

[functions.create-r2-upload-urls]
verify_jwt = true

[functions.proxy-r2-upload]
verify_jwt = true
